### Get list of users
GET http://localhost:8080/api/user/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiS3JhbnRpIiwiaWF0IjoxNzA3OTk0NDQyLCJleHAiOjE3MDc5OTgwNDJ9.nXniLQAzxbqk-ZyoRWh0A-AmLG05D0vOcGGjFRnLDLo

### Get single user
GET http://localhost:8080/api/user/kranti@test.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiS3JhbnRpIiwiaWF0IjoxNzA3OTk0NDQyLCJleHAiOjE3MDc5OTgwNDJ9.nXniLQAzxbqk-ZyoRWh0A-AmLG05D0vOcGGjFRnLDLo

### Create a new user
POST http://localhost:8080/api/user/signup
Content-Type: application/json

{
  "name": "Kranti",
  "email": "kranti@test.com",
  "password": "123456"
}

### Sign In 
POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
  "email": "kranti@test.com",
  "password": "123456"
}


### Update User's Profile 
PATCH http://localhost:8080/api/user/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInVzZXJuYW1lIjoidXNlciIsImlhdCI6MTcwNzgyNjIwMywiZXhwIjoxNzA3ODI5ODAzfQ.N7-PKDjDw64pB6fP0ArVFqUF34FvvEmhf3DLJle8UYs

{
  "email": "kranti@test.com",
  "description": "I am a software engineer"
}

